#总目标的依赖文件最多
TestR20.class:	TestR20.java qiuni2.java qiuni2.class Rational2.java Rational2.class
		javac TestR20.java
		java TestR20	
qiuni2.class:	qiuni2.java Rational2.java
		javac qiuni2.java
Rational2.class:	Rational2.java
		javac Rational2.java